apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: myapp-letsencrypt-staging
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-stating.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: juanp_perez@msn.com
    privateKeySecretRef:
      name: myapp-letsencrypt-staging
    # Enable HTTP01 validations
    http01: {}
